### 라이브러리(모듈)
- 변수,함수,클래스들을 모아 놓은 파일

### 데이터 분석에 특화된 라이브러리
- Numpy : 고성능 과학계산을 위한 데이터 분석 라이브러리
- Pandas : 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리
- Matplotlib : 2D 그래프로 시각화가 가능한 라이브러리

### NumPy의 주요기능
- 빠르고 효율적인 벡터 산술연산을 제공하는 다차원배열 제공
(ndarray 클래스)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수
(sum(),sqrt(),mean())

※ sqrt : square root

### 라이브러리 사용하기
- numpy 라이브러리를 import하고 앞으로 np라는 이름으로 부름

import numpy as np

### Numpy
- 수학/과학 계산을 위한 라이브러리로서 다차원 배열을 처리하는데 필요한 여러 기능들을 제공함

In [1]:
import numpy as np

In [2]:
list_ = [1,2,3,4,5]
list_

[1, 2, 3, 4, 5]

In [3]:
arr = np.array(list_)  #ndarray(다차원배열)을 실행하는 명령은 np.array
arr

array([1, 2, 3, 4, 5])

In [4]:
# 2차원 배열
arr2 = np.array( [[1,2,3], [4,5,6]] )
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 배열의 크기(행, 열) 가로:행 세로:열
arr2.shape

(2, 3)

In [6]:
# 배열의 요소 전체 개수
arr2.size

6

In [9]:
# 배열의 타입(자료형 확인)
# 배열은 리스트와는 다르게 한 종류의 자료형으로만 구성되어야 함
arr2.dtype

# int뒤의 숫자 32는 bit를 뜻함(기계가 표현할 수 있는 범위) -> 2^32 (2의 32승)

# int8 -> 1비트당 2개의 숫자를 표현(0, 1)
#          8비트는 2^8 = 256(범위는 -128 ~ 127)

dtype('int32')

In [7]:
# 배열의 차원 확인
arr2.ndim

2

In [10]:
arr3 = np.array( [ [ [1,2],[3,4] ],[ [5,6],[7,8 ] ] ])

In [11]:
# arr3 배열의 크기, 차원, 전체요소 개수를 출력해보세요~!
print("배열의 크기:", arr3.shape)
print("배열의 차원:", arr3.ndim)
print("배열의 전체개수:", arr3.size)

배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 전체개수: 8


In [12]:
# 0으로 배열 생성
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# 1로 배열 생성
arr_ones = np.ones((3,4,3))   # (개수, 행, 열)
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [14]:
# 특정값으로 배열생성
arr_full = np.full((5,5), 2)    #5행 5열의 배열을 2로 채워준다
arr_full

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [15]:
# 1~ 50까지 배열 생성
# 리스트 생성후 배열로 변환시켜보세요~!

list_ = []

for i in range(1,51,1):
    list_.append(i)
    
print(list_)

np.array(list_)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
# 반복문을 사용하지 않고 배열 생성
arr5 = np.arange(1,51,1)   #시작, 끝, 증감량
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
# 1부터 51까지 중에서 1, 11, 21, 31, 41로 배열을 생성해보세요~!

arr6 = np.arange(1,51,10)
arr6

array([ 1, 11, 21, 31, 41])

In [19]:
arr7 = np.arange(1,51)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
# reshape : 배열의 행과 열을 재설정해주는 명령
# 현재는 출력만 되게 코드를 작성했음, 실제로 값을 업데이트 시켜줄려면 변수에 넣어줘야함
arr7.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [21]:
arr7 =arr7.reshape(10,5)

In [22]:
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [23]:
# 배열의 자료형 변경
arr8 = np.array([1.2, 2.3, 3.4], dtype = np.int64) # 64비트의 정수형으로 변경
arr8

array([1, 2, 3], dtype=int64)

In [24]:
arr9 = np.array([1,2,3], dtype=np.float32)
arr9

array([1., 2., 3.], dtype=float32)

In [25]:
# 랜덤 정수 값 생성하기
# (그냥 random.randint는 뒷 숫자 포함이지만 np 명령은 뒷 숫자 미포함)
arr10 = np.random.randint(3)
arr10

1

In [26]:
import random

In [27]:
random.randint(1,3)

2

In [28]:
# 랜덤 값 배열 생성하기
# rand : 0~1 사이 값을 랜덤하게 생성
arr11 = np.random.rand(2,3)  #2행 3열 값을 배열로 생성
arr11

array([[0.16119584, 0.56605654, 0.51082577],
       [0.44055466, 0.72546604, 0.74626793]])

In [29]:
# 랜덤 값 정수형 배열 생성하기
arr12 =np.random.randint(5, size=10)  # 5 : 0~4사이값 중에서 랜덤하게 10개 생성
arr12

array([2, 3, 2, 4, 0, 2, 2, 3, 4, 3])

In [30]:
arr13 =np.random.randint(5, size=(2,3))
arr13

array([[3, 0, 0],
       [1, 3, 0]])

#### 랜덤 시드 (random seed) 설정

In [31]:
#랜덤 시드 설정
np.random.seed(5555)
np.random.randint(5, size=(2,3))

array([[2, 4, 2],
       [2, 3, 3]])

### array 연산

In [32]:
arr14 = np.array( [ [1,2], [3,4] ])
arr14

array([[1, 2],
       [3, 4]])

In [33]:
arr14+arr14

array([[2, 4],
       [6, 8]])

In [34]:
arr14 * arr14

array([[ 1,  4],
       [ 9, 16]])

In [35]:
arr14 / arr14

array([[1., 1.],
       [1., 1.]])

In [36]:
arr14 % arr14

array([[0, 0],
       [0, 0]], dtype=int32)

In [37]:
arr15 = np.arange(2,10,2)
arr15

array([2, 4, 6, 8])

In [38]:
arr15 * 2

array([ 4,  8, 12, 16])

### Numpy 배열의 접근은 어떻게 해야 할까?
- numpy는 파이썬 리스트와 마찬가지로 인덱싱, 슬라이싱 지원함

### 1.numpy 인덱싱

In [21]:
arr16 = np.array([ [1,2,3], [4,5,6] ])
arr16

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr16[0]

array([1, 2, 3])

In [ ]:
arr16[0][1]

#### 2.numpy 슬라이싱

In [ ]:
arr17 = np.arange(10)
arr17

In [ ]:
arr17[3:8] = 10

In [ ]:
arr17

In [40]:
arr18 = np.arange(50).reshape(5,10)
arr18

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
# 첫번째, 두번째 행을 모두 출력
arr18[0:4, : ]   # arr18[행의범위, 열의범위]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [42]:
arr18[:, 0] # 모든 행의 0번째 열을 출력

array([ 0, 10, 20, 30, 40])

In [43]:
# 1번 인덱스 행까지와 7번 인덱스 열부터 끝까지 접근
arr18[:2, 7: ]

array([[ 7,  8,  9],
       [17, 18, 19]])

In [44]:
arr19 = np.arange(18).reshape(3,6)
arr19

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [45]:
# 방법 1
arr19[1:, [1,3,5]]

array([[ 7,  9, 11],
       [13, 15, 17]])

In [46]:
# 방법 2
arr19[1:, 1::2]  # 1번 열 인덱스 부터 2씩 증가

array([[ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
# 배열의 행과 열을 바꾸기
arr19

In [ ]:
arr19.T

In [ ]:
arr19 = arr19.T

In [ ]:
arr19

### Numpy 불리언 인덱싱
- 특정 조건에 맞으면 True, 아니면 False값으로 배열을 만들어 조건에 맞는 값에 접근하는 방식

In [47]:
# 50 ~ 99까지의 범위에서 8개의 값을 가지는 1차원 배열을 생성
arr20 = np.array(np.random.randint(50, 100, size=8))
arr20

array([66, 66, 62, 94, 85, 58, 63, 98])

In [48]:
arr20 >= 70

array([False, False, False,  True,  True, False, False,  True])

In [49]:
# arr20 배열에서 짝수인 값을 판단
arr20 % 2 == 0

array([ True,  True,  True,  True, False,  True, False,  True])

In [50]:
# True, False가 아닌 실제 값을 보고 싶을 경우
# 배열명[배열 내에서 찾고자 하는 조건] -> True 값만 출력이 됨
arr20[arr20 % 2 == 0]

array([66, 66, 62, 94, 58, 98])

In [51]:
arr20[arr20 >= 70]

array([94, 85, 98])

In [3]:
# 다음 2차원 배열에서 값이 짝수이면 0으로 변경하는 코드를 작성해보자~!
arr = np.array( [ [6,9,6,8,7], [2,3,5,4,1]
                ])
arr[arr%2==0] = 0       # arr%2==0 자체가 조건이 됨
arr

array([[0, 9, 0, 0, 7],
       [0, 3, 5, 0, 1]])

array([[12,  9, 12,  8,  7],
       [ 2,  3,  5,  4,  1]])